---
# This is a workflow meant for epitech students

name: CI Epitech Project

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Triggers the worlfow every day at 23h42
  # schedule:
    # - cron: "42 23 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "DockerEpitech"
  DockerEpitech:

    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker:latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a bash file that builds the projet using CMake
      - name: CMake IndieStudio
        run: |
          bash .github/scripts/build.sh

  # This workflow contains a single job called "TestDrivenDevelopement"
  TestDrivenDevelopement:

    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker:latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a bash file that executes unit tests (with criterion)
      - name: Execute Criterion testing sequences
        run: |
          bash .github/scripts/unit_tests.sh

  # This workflow contains a job called "EpitechPromo2025"
  EpitechPromo2025:
    # This job requires GithubPrerequisites AND AnsiblePlaybook successful run to push
    needs:
      - DockerEpitech
      - TestDrivenDevelopement

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Pushes to Epitech official repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
          USER_EMAIL_GITHUB: ${{ secrets.USER_EMAIL_GITHUB }}
        with:
          source-directory: 'project/'
          destination-github-username: 'EpitechPromo2025'
          destination-repository-name: 'B-YEP-410-PAR-4-1-zappy-martin.vanaud'
          user-email: ${{ secrets.USER_EMAIL_GITHUB }}
          commit-message: See ORIGIN_COMMIT from $GITHUB_REF
          target-branch: master
      - name: Test get variable exported by previous action
        run: echo $DESTINATION_CLONED_DIRECTORY
